services:
  backend-api:
    build: ./backend
    container_name: backend-api
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network
    depends_on:
      - backend-api
  
  redis:
    image: "redis:7-alpine"
    container_name: my_app_redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
